// <auto-generated />
namespace M226B_Rental_Proj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class License : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(License));
        
        string IMigrationMetadata.Id
        {
            get { return "202011081343425_License"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
